GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzaGEiLCJpZCI6MiwiaWF0IjoxNjk2Nzc3MDM0fQ.6sLJARDsxY6JJ4ryn0SfRqHc5fHc03DJBdF0Q_IpDK4

{
   "author":"usha",
   "title":"blogsecond from usha",
   "url":"www.kathmandu.post",
   "likes":4
   
}

###
PUT http://localhost:3001/api/blogs/3
Content-Type: application/json

{
  "likes":6
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username":"usha",
  "name":"usha",
  "password":"123"

}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username":"usha",
  "password":"123"

}

###
PUT  http://localhost:3001/api/users/raju
Content-Type: application/json

{
  "username":"KAJU"
  
}

###
DELETE http://localhost:3001/api/blogs/3
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYXRpa3NoYXJhaTcyOEBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjk2NzYwMDUyfQ.O7ELThUSU2sCPgcAP5oyaFQjw4HIqqWWNnGEwD4-0wU

###
GET http://localhost:3001/api/authors