GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
   "author":"",
   "title":"another note second",
   "url":"www.kathmandu.post",
   "likes":0
}

###
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes":8
}