GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxheG1pIiwiaWQiOjEsImlhdCI6MTY5Njc3ODA5MX0.6LyjKNBWG2M7v8gMkw0P0VD5zvvlqB7odO2pznYM_u0

{
   "author":"usha",
   "title":"test",
   "url":"www.kathmandu.post",
   "likes":4,
   "year":2025
   
}

###
PUT http://localhost:3001/api/blogs/3
Content-Type: application/json

{
  "likes":6
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username":"laxmi",
  "name":"usha",
  "password":"123"

}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username":"laxmi",
  "password":"123"

}

###
PUT  http://localhost:3001/api/users/raju
Content-Type: application/json

{
  "username":"KAJU"
  
}

###
DELETE http://localhost:3001/api/blogs/3
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYXRpa3NoYXJhaTcyOEBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjk2NzYwMDUyfQ.O7ELThUSU2sCPgcAP5oyaFQjw4HIqqWWNnGEwD4-0wU

###
GET http://localhost:3001/api/authors


###
POST http://localhost:3001/api/blogs/reading
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzaGEiLCJpZCI6MiwiaWF0IjoxNjk2Nzg0MjY4fQ.BPDTOWkt-M7HV28k9nJEokROz54o5imPxECPY67XEOA

{
   "blogId":"5",
   "userId":"2",
   "isRead":"false"
   
   
}

###
GET http://localhost:3001/api/blogs/reading


###
PUT  http://localhost:3001/api/blogs/reading/6
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxheG1pIiwiaWQiOjEsImlhdCI6MTY5Njc4NjM4M30.Sm13ewtB19DjWON7nyprt5yYaVc23nKHdyhovln0MUo

{
   
   "isRead":"false"

   
}